######################################################################
# Automatically generated by qmake (2.01a) jeu. 4. sept. 13:16:49 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MonThread.h prestations.h
FORMS += prestations.ui
SOURCES += main.cpp MonThread.cpp prestations.cpp
