######################################################################
# Automatically generated by qmake (2.01a) lun. 8. sept. 17:44:25 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MonThread.h nouvproj.h prestations.h
FORMS += nouvproj.ui prestations.ui
SOURCES += main.cpp MonThread.cpp nouvproj.cpp prestations.cpp
